In [7]:
import numpy as np
a = np.arange(4*32*128*128).reshape((4, 32, 128, 128))
b = np.ones((4, 32, 128, 128))

In [9]:
a[:,:,[0,1,2],[0,1,2]].shape

(4, 32, 3)

In [13]:
a[:,:,[0,1,2],:][:,:,:,[0,1,2]]#.shape

array([[[[      0,       1,       2],
         [    128,     129,     130],
         [    256,     257,     258]],

        [[  16384,   16385,   16386],
         [  16512,   16513,   16514],
         [  16640,   16641,   16642]],

        [[  32768,   32769,   32770],
         [  32896,   32897,   32898],
         [  33024,   33025,   33026]],

        ...,

        [[ 475136,  475137,  475138],
         [ 475264,  475265,  475266],
         [ 475392,  475393,  475394]],

        [[ 491520,  491521,  491522],
         [ 491648,  491649,  491650],
         [ 491776,  491777,  491778]],

        [[ 507904,  507905,  507906],
         [ 508032,  508033,  508034],
         [ 508160,  508161,  508162]]],


       [[[ 524288,  524289,  524290],
         [ 524416,  524417,  524418],
         [ 524544,  524545,  524546]],

        [[ 540672,  540673,  540674],
         [ 540800,  540801,  540802],
         [ 540928,  540929,  540930]],

        [[ 557056,  557057,  557058],
         [ 557184,

In [16]:
A = np.arange(8).reshape((2,2,2))

In [17]:
A

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [29]:
B = np.ones((2,1))

In [30]:
B

array([[1.],
       [1.]])

In [32]:
np.einsum('abc,cd->abd', A, B).shape

(2, 2, 1)

In [35]:
a.shape, b.shape

((4, 32, 128, 128), (4, 32, 128, 128))

In [37]:
b = np.ones((4, 32, 9, 9, 128, 128))

In [38]:
np.tensordot(a,b, axes=[[1], [1]])

MemoryError: 